# A config for a Warp Route deployment
# Typically used with the 'hyperlane deploy warp' command
#
# Token Types:
#   native
#   collateral
#   synthetic
#
# see comprehensive [list](https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/typescript/sdk/src/token/config.ts#L8)
---
gethlocal:
  type: synthetic
  # token: "0x123" # Collateral/vault address. Required for collateral types
  owner: "0xA5D139cA25544F4560d1c7EF0cFd58109417Cdd1" # Optional owner address for synthetic token
  mailbox: "0x067A3faF94e52886bEBe17665aA9C395A8cB08Dd" # mailbox address route (INJECTIVE MAILBOX)
  # interchainGasPaymaster: "0x123" # Optional interchainGasPaymaster address
  isNft: false # If the token is an NFT (ERC721), set to true
  # You can optionally set the token metadata
  name: "Hyperlane INJ"
  decimals: 18
  symbol: "hINJ"
  totalSupply: 10000000
  interchainSecurityModule:
    relayer: "0xA5D139cA25544F4560d1c7EF0cFd58109417Cdd1"
    type: trustedRelayerIsm
  hook:
    type: merkleTreeHook