[package]
name = "authzethtx"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "3.0.2", features = ["cosmwasm_2_0"] }
cosmwasm-schema = "3.0.2"
prost={ version = "0.14.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
hex = "0.4"
serde_json = "1.0.120"
rlp = "0.5.2"
bytes = "1.10.0"
prost-types = "0.14.1"
